---
# tasks file for kafka

- name: 清除旧数据及旧容器
  shell: 'docker-compose -f {{ OPT_PATH }}/{{ KAFKA_CONTAINER_NAME }}/docker-compose.yaml rm -fsva;rm -rf {{ OPT_PATH }}/{{ KAFKA_CONTAINER_NAME }}'
  ignore_errors: yes

- name: 创建部署目录
  shell: '[[ ! -d "{{ OPT_PATH }}/{{ KAFKA_CONTAINER_NAME }}" ]] && mkdir -vp {{ OPT_PATH }}/{{ KAFKA_CONTAINER_NAME }}'
  ignore_errors: yes

- name: 创建持久化目录
  shell: '[[ ! -d "{{ SRV_PATH }}/{{ KAFKA_CONTAINER_NAME }}" ]] && mkdir -vp {{ SRV_PATH }}/{{ KAFKA_CONTAINER_NAME }}; chmod 777 {{ SRV_PATH }}/{{ KAFKA_CONTAINER_NAME }}'
  ignore_errors: yes

- name: 配置环境变量
  copy: src=files/{{ KAFKA_CONTAINER_NAME }}.env dest={{ OPT_PATH }}/{{ KAFKA_CONTAINER_NAME }}/.env

- name: 配置 kafka docker-compose.yaml
  template: src=docker-compose.yaml.j2 dest={{ OPT_PATH }}/{{ KAFKA_CONTAINER_NAME }}/docker-compose.yaml

- name: 运行服务
  shell: 'docker-compose -f {{ OPT_PATH }}/{{ KAFKA_CONTAINER_NAME }}/docker-compose.yaml up -d'